version: '3.8'

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${PPOSTGRES_DB}
    volumes:
      - pushnoti_api_pg_data:/var/lib/postgresql/data

  api:
    user: 'node'
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - DOCKER_UID=1000
        - DOCKER_GID=1000
    ports:
      - '3000:3000'
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    env_file:
      - .env

  pg_admin:
    image: dpage/pgadmin4:8.2
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:80

volumes:
  pushnoti_api_pg_data: